# Site settings
title: "kumar18tushar"
email: kumar18tushar@gmail.com
description: "My personal blog"
baseurl: ""
url: "http://kumar18tushar.github.io/"
title_description: "This is my personal blog where I prefer to discuss the concepts related to various programming problems."
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-128217400-1"
disqus_account: 
github_repository: https://github.com/kumar18tushar/kumar18tushar.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  kumar18tushar
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: //plus.google.com/116619499162789899432
stackoverflow_link: 
xing_link:
facebook_link: https://www.facebook.com/tushar.singh.56027281

# Footer
footer_left: "     Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://www.facebook.com/tushar.singh.56027281\">kumar18tushar</a>"
footer_right: 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
